### ISSUE TITLE
Make Env an interface type

### ISSUE THREAD

**Issue by 0xfaded** [0xfaded/eval#39]
@rocky 

I've been thinking about how to deal with the EvalIdent hook now that there is also the checkIdent function that will need to be hooked.

What I think may be a nicer solution would be to make Env an interface type and allow the user to provide their own implementation if that is what is convenient. Would this solve your woes with regards to converting ssa values to eval values?

**Comment by rocky** [comment]
It's not just EvalIdent and CheckIdent. Right now there is also a hook for converting a reflect.Value into a value of some other form. And a function for evaluating a selector expression.

Changing Env to some sort of interface type is reasonable. So I suggest making a branch and trying it out.

**Comment by 0xfaded** [comment]
I saw that ing gub. Could the converter live in the Env implementation?

**Comment by rocky** [comment]
It can probably, but it doesn't make a lot of sense. Feynman once said you can "unify" all sorts of independent facts, but that doesn't necessary make for a simpler theory. 

The conversion routine takes a reflect.Value and converts that into the kind of value the ssa-interpreter uses. I don't see what that has to do with the evaluation environment per se.

**Comment by 0xfaded** [comment]
As I understand it, the need for the hook stems from the need to feed
values of a differing source/format into the evaluation context. If the
values are read from the environment in a predictable manner, then I would
expect that being in control of that lookup process would be enough to feed
whatever values one wants into the evaluator.

As you can probably tell, I'm not too keen on the hooks, especially if
there wind up being several of them.

Carl
2014/01/16 20:00 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
While I am agnostic as to how or the mechanism used to solve the problem, I do think that it important to solve the problem. 

Also, I don't think this statement: 

> the need for the hook stems from the need to feed values of a differing source/format into the evaluation context.

is a proper characterization of the situation or the right way to think about this.

That there are differing ways to represent values is one facet. But there is a second facet in that the entire evaluation process one would like to be generic. This is similar to the way Go's sort routine is generic. And, yes,  interfaces are the way Go implements a generic sort routine here.

What I think will be constant in the evaluation process is that one will always work off of a go ast. How one accesses the ast will always be the same, and the broad structure of breaking down sub-expressions and the broad steps of directing what pieces need to be evaluated. The choice of whether to do type checking first or as the evaluation goes on could probably be hidden, whichever choice one uses. 

However what I think will be inescapable is the fact that the way specific operations of evaluation get implemented need to be flexible and not totally under control of the evaluator.  We mentioned looking up the value of an identifier or accessing a field of a structure. To be sure, in accessing a structure, even though on the AST side the pieces for parsing x.y are always the same. How you get the new value from structure x with field member y should be pluggable. 

The other area that I haven't mentioned in that league is how to implement function calls and return values. Again from the AST side, for _f(x,y,z)_ one needs to bundle up the call arguments and look up _f_ and check the function signature. But when it comes to evaluating _f(x,y,z)_ and passing return values back, the details may be totally different in the ssa interpreter than how it is done currently in eval. The ssa interpreter may ultimately choose to implement a eval'd function call by calling the interpreter routine to interpret the function because that code might not exist in the compiled go code that was used to build the interpreter.

Can providing specifics for implementing specific evaluation operations be done via interfaces?  The go _sort_ routine seems to suggest the answer is yes.  But is this about the evaluation context or environment? I don't see it. I see it as being about generics and being able to provide specific operations to an otherwise generic process. 

(Generic here doesn't mean that things are not fixed, just that it handles multiple types. For example go's sort routine might in fact use quicksort which is s a very specific kind of implementation among general sorting algorithms.)

**Comment by 0xfaded** [comment]
I think its important to provide a flexible enough interface without
introducing a huge amount of complexity to the api. In the case you
mentioned, with function calls, I would suggest converting the function to
a reflect.Value using reflect.MakeFunc to wrap a closure around the SSA
implementation of the function call.

This of course brings us back to the question of what types/code is
compiled into the debugger, as you need a reference to the function type to
call MakeFunc. You likely won't have that if you are interpreting from the
source.

My proposed solution is to write a new package called refract, which
provides an emulation layer on top of reflect with the additional
functionality to declare new types. It would basically be a 1:1 mapping to
the underlying reflect package, with a couple new methods for declaring new
types. That would allow you to implement a Env.Func(name string) lookup
method which creates a new reflect.Value func type and returns it.

Especially with the type checking, I am very cautious about opening up the
internal machinery as the checker makes many internal annotations on the
ast which must be set, not to mention the lost error messages.

Carl
2014/01/16 23:15 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
I don't see how type checking is involved with things like 
- here's the name of a structure, and here's the name of a member in that, go give me a reflect value for the result
- here's the name of a function and here are the parameter lists, evaluate that and give me the results

If one does type checking first that's okay. If you for some reason you need the evaluation to return the type of the result, that's not a big deal either.

But that said, It is possible some sort of layer or package to mediate between different kinds of values will help. I'm mot convinced it's going to handle all the issues that need to be addressed, but it's all in the details.  I think it wil beome clear when someone actually starts to try this.

**Comment by 0xfaded** [comment]
Quite simply, the type checker is involved because when checking that the
type or function can be used in its context, it needs to first check that
it exists. Perhaps I have misunderstood your examples.

Carl
2014/01/17 21:51 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
Yes, a type checker is involved in checking the signature and types of return types. 

It is not involved with answering the question how one computes a value for the function given specific argument values. Furthermore, I  don't see how what ast annotations are used how they are set, makes it unsafe or exposed to yield back to a function outside of eval to compute the value of a call or to compute the value of getting the value of a field inside a structure.

**Comment by 0xfaded** [comment]
For evaluation yes, this could go to an external routine. But if youre
trying to avoid building an environment by hijacking certain points in the
evaluation routine, then you're going to need to patch up the type checking
routines as well.

Carl
2014/01/18 0:23 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
> But if you[']re trying to avoid building an environment by hijacking certain points in the evaluation routine

Where did you get the impression that this was going on? The ssa interpreter has a ready built up environments it needs. It is true though that a way to call an outside routine to check whether specific call sites match call function signatures and a way to  specify what the return types are for a given function name is needed.

**Comment by 0xfaded** [comment]
Sorry, I should have phrased that trying to avoid building a duplicate
eval.Env. This is the solution I envision in client code

```
type Env SSAEnv
func (e Env) Var(ident string) reflect.Value {
    ssaEnv := SSAEnv(e)
    ssaValue := ssaEnv.Var(ident)
    evalValue := doSomeMagic(ssaValue)
    return evalValue
}
```

Now, you talk about how would function calls be evaluated. From my
perspective, I would ask what sort of value must I return for my function
call to work. I envision something like this

```
   fun := ssaFun
   ftype := refract.FuncOf(inTypes, outTypes)
   evalFun := refract.MakeFunc(ftype, func(a int, b bool) int {
       ssaValue := ssaEvalFunc(fun, a, b)
       return ssaValue.ConvertToGoType()
   }
   return evalFun
}
```

Yes I admit that wrapping the function calls is a little cumbersome, but at
the same time you now have the means to control how function evaluation.
I'm really not sure what more is needed.

Sorry for the lag, phone coding is also cumbersome

Carl
2014/01/18 0:35 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
> Yes I admit that wrapping the function calls is a little cumbersome

And the implementation of refract.FuncOf is going to be complicated because it has to parse the in types and out types, compose  a custom conversion routine for the combination of the in and out signature and then relect-encode that.

So what's the downside instead having the eval call handle this instead by control by passing the function name, a slice of input parameter values and a slice of output parameter values? I don't see what's been gained by the closure.

**Comment by 0xfaded** [comment]
Refract is going to be necessary to define new types regardless, but I
don't think it will be too difficult. I have no intention of trying to
interface directly with the runtime (yet), all I need is a simple emulation
layer where I can control what happens to types defined by refract. Call
refract.MakeFunc on an underlying reflect.Type and I'll throw it through to
the reflect package. Call it on a refract.FuncType and I'll return a
refract.FuncValue with a call method that basically just passes the
arguments through to the closure.

From what it sounds like you now want a hook where you can evaluate
function calls (what about built ins and type conversions?), another one
where you can check function calls (do to really want to reimplement that
logic?) and more hooks for identifier and package evaluation (again, and
checking those?). From the points you've raised thus far, there is nothing
couldn't be done by creating an environment containing whatever is of
interest. I'll concede that for the, somewhat unlikely, use case where one
wants to interface between evaluators this is a burden, but I believe that
allowing the client to define its own Env  implementation for the most part
alleviates this.

Carl
2014/01/18 10:56 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
I think enough has been written about this. I have a number of other things I need to focus on over the next week or two.
