### ISSUE TITLE
column position in eval.ParseStmt a little funcky

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#49]
Running: 

``` go
package main
import ( "github.com/0xfaded/eval" )
func main() {
    if _, err := eval.ParseStmt("type"); err != nil {
        println(err.Error())
    }
}
```

gives: 

```
parse error: 1:12: expected 'IDENT', found '}'
```

Column 12 is larger than the string. What gives?

**Comment by 0xfaded** [comment]
Types are Decls, not Statements or Exprs, so therefore what you are doing
there is technically invalid. However, I agree, it could be nicer.
What has actually happened is eval.EvalStmt works by wrapping the
expression in an otherwise empty function literal, so what got parsed was
func(){type}

Now, I went through and subtracted 7 from the error pos, but it seems this
was not reflected in the error message, possibly because it is stored
as a static string and not formatted on each Error() call. I'll look into
it.

On Tue, Feb 18, 2014 at 2:25 PM, R. Bernstein notifications@github.comwrote:

> package mainimport ( "github.com/0xfaded/eval" )func main() {
>     if _, err := eval.ParseStmt("type"); err != nil {
>         println(err.Error())
>     }}
> 
> gives:
> 
> parse error: 1:12: expected 'IDENT', found '}'
> 
> Column 12 is larger than the string. What gives?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/0xfaded/eval/issues/49
> .

## 

Carl

**Comment by 0xfaded** [comment]
go> type
type
----^
1:5: expected 'IDENT', found ';'

Fixed

Basically the error had two relevant fields, Offset and Column. I was only
modifying Offset.
I also added a ; to the parsed function lit, so now you get found ';'
instead of '}'.

On Tue, Feb 18, 2014 at 2:50 PM, Carl carlchatfield@gmail.com wrote:

> Types are Decls, not Statements or Exprs, so therefore what you are doing
> there is technically invalid. However, I agree, it could be nicer.
> What has actually happened is eval.EvalStmt works by wrapping the
> expression in an otherwise empty function literal, so what got parsed was
> func(){type}
> 
> Now, I went through and subtracted 7 from the error pos, but it seems this
> was not reflected in the error message, possibly because it is stored
> as a static string and not formatted on each Error() call. I'll look into
> it.
> 
> On Tue, Feb 18, 2014 at 2:25 PM, R. Bernstein notifications@github.comwrote:
> 
> > package mainimport ( "github.com/0xfaded/eval" )func main() {
> >     if _, err := eval.ParseStmt("type"); err != nil {
> >         println(err.Error())
> >     }}
> > 
> > gives:
> > 
> > parse error: 1:12: expected 'IDENT', found '}'
> > 
> > Column 12 is larger than the string. What gives?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/0xfaded/eval/issues/49
> > .
> 
> ## 
> 
> Carl

## 

Carl
